# File: .github/workflows/repo-sync.yml

on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/murad357/parent-repo.git"
        source_branch: "development"
        #destination_repo: "https://murad357:10Wandering!g@github.com/murad357/child-repo1.git"
        destination_repo: "https://github.com/murad357/child-repo1.git"
        destination_branch: "development"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}