# File: .github/workflows/repo-sync.yml

on: 
  push:
    branches: [ development ]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://github.com/murad357/parent-repo.git"
        source_branch: "development"
        destination_repo: "https://murad357:51bcc29a835ad40b76a4a1e1a58b0a521ec3bf37@github.com/murad357/child-repo1.git"
        destination_branch: "development"
        #ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}